version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
      args:
        - DEV=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_React:/frontend_React
    command: >
      sh -c "npm  install && npm start"
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/libs/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
  
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  dev-db-data: